// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Api.Endpoints.Base.Generator;

namespace InfoportOneAdmon.Back.Api.Endpoints.Base
{
    public static class GenericEndpoints
    {
        public static void MapGenericEndpoints(this WebApplication app)
        {
            
        }
    }
}