// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.DataModel.Base;
using InfoportOneAdmon.Back.Entities.Views.Base;
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain;
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Endpoints;
using Helix6.Base.Domain.Parameters;
using Helix6.Base.Domain.Security;
using Helix6.Base.Helpers;
using Helix6.Base.Service;
using Microsoft.AspNetCore.Mvc;

namespace InfoportOneAdmon.Back.Api.Endpoints.Base.Generator
{
    public static class VTA_AttachmentEndpoints
    {
        /// <summary>
        /// Maps selected endpoints of the entity <type>VTA_Attachment</type>.
        /// </summary>
        /// <param name="app"></param>
        public static void MapVTA_AttachmentEndpoints(this WebApplication app)
        {
            EndpointHelper.GenerateGetAllKendoFilterEndpoint<IBaseService<VTA_AttachmentView, VTA_Attachment, VTA_AttachmentViewMetadata>, VTA_AttachmentView, VTA_Attachment, VTA_AttachmentViewMetadata>(app, "/api/VTA_Attachment/GetAllKendoFilter", new EndpointAccess(HelixEnums.SecurityLevel.Read));
        }

        public static void GenerateGetAllVTAAttachmentsKendoFilterEndpoint<TBaseService, TViewBase, TEntityBase, TViewBaseMetadata>(WebApplication app, string route, EndpointAccess endpointAccess, params string[] schemas)
          where TBaseService : IBaseService<TViewBase, TEntityBase, TViewBaseMetadata>
          where TEntityBase : class, IEntityBase
          where TViewBase : class, IViewBase
          where TViewBaseMetadata : class, IViewBaseMetadata
        {
            app.MapPut(route, async ([FromServices] TBaseService service, IUserPermissions userPermissions, IGenericFilterMapping genericFilterMapping, IBaseService<VTA_AttachmentView, VTA_Attachment, VTA_AttachmentViewMetadata> vtaAttachmentService, [FromBody] KendoGridFilter kendoGridFilter, [FromQuery] int id, string configurationName, bool? includeDeleted) =>
            {
                var validateAccess = await EndpointHelper.ValidateAccess<TEntityBase>(endpointAccess, userPermissions);
                if (!validateAccess) return Results.Forbid();

                includeDeleted ??= false;

                var entityName = service?.EntityName;
                if (entityName == null)
                    entityName = typeof(TEntityBase).Name;

                KendoFilter kendoFilterId = new()
                {
                    Field = "entityId",
                    Operator = "=",
                    Value = id
                };
                KendoFilter kendoFilterName = new()
                {
                    Field = "entityName",
                    Operator = "=",
                    Value = entityName
                };

                kendoGridFilter.Data.Filter.Filters.Add(kendoFilterId);
                kendoGridFilter.Data.Filter.Filters.Add(kendoFilterName);

                IGenericFilter iGenericFilter = null;
                if (kendoGridFilter != null)
                    iGenericFilter = genericFilterMapping.MapKendofilter(kendoGridFilter, typeof(VTA_AttachmentView));

                PagingResponse pagingResponse = new()
                {
                    List = await vtaAttachmentService.GetAll(new QueryParams(configurationName, includeDeleted.Value), iGenericFilter),
                    Count = await vtaAttachmentService.CountGetAll(includeDeleted.Value, iGenericFilter)
                };
                return Results.Ok(pagingResponse);

            }).Produces(StatusCodes.Status200OK, typeof(PagingResponse))
            .WithSummary("Obtiene la lista de todos los adjuntos de una entidad aplicando un filtro complejo proporcionado por la grid de Kendo Telerik.")
            .WithDescription("<H3>Parametros:</H3><br>" +
                            "<li>KendoGridFilter: Objeto de filtrado generado por la grid de Kendo Telerik. Este parámetro se recibe en el request payload.<br>" +
                            "<li>Id: Identificador de la entidad a la que se vincula el adjunto.<br>" +
                            "<li>AttachmentTypeId: Parámetro opcional que indica el tipo de adjunto.<br>" +
                            "<li>ConfigurationName: Indica la configuración de carga. Si no se indica toma la configuración de carga por defecto de la entidad.<br> " +
                            "<li>IncludeDeleted: Incluye o no los elementos de baja lógica. Si no se indica toma el valor false.<br><br>" +
                            "<H3>Ejemplos:</H3><br>" +
                            "<li><b>" + route + "?Id={id}</b> Obtiene la lista de adjuntos de la entidad con ese id filtrados por el filtro de la grid con su configuración de carga por defecto sin incluir las entidades de baja.<br>" +
                            "<li><b>" + route + "?Id={id}&configurationName={configuration}</b> Obtiene la lista de adjuntos de la entidad con ese id filtrados por el filtro de la grid para una configuración de carga concreta sin incluir las entidades de baja.<br>" +
                            "<li><b>" + route + "?Id={id}&includeDeleted=true</b> Obtiene la lista de adjuntos de la entidad con ese id filtrados por el filtro de la grid con su configuración de carga por defecto incluyendo las entidades de baja.<br>" +
                            "<li><b>" + route + "?Id={id}&configurationName={configuration}&includeDeleted=true</b> Obtiene la lista de adjuntos de la entidad con ese id filtrados por el filtro de la grid para una configuración de carga concreta incluyendo las entidades de baja.")

            .WithOpenApi().RequireAuthorization(schemas)
            .WithTags($"{typeof(TEntityBase).Name}");
        }
    }
}