// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(PermissionsViewMetadata))]
    public partial class PermissionsView: IViewBase	
	{
		public Int32 Id { get; set; }

		public Int32 SecurityAccessOptionId { get; set; }

		[StringLength(200)]
		public String SecurityAccessOption { get; set; }

		[StringLength(200)]
		public String Controller { get; set; }

		public Int32? SecurityLevel { get; set; }

		[StringLength(200)]
		public String Profile { get; set; }

		[StringLength(100)]
		public String Rol { get; set; }

		[StringLength(200)]
		public String Module { get; set; }

		public Int32? SecurityCompanyId { get; set; }

		[StringLength(200)]
		public String SecurityCompany { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }
	}
}

