// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(SecurityModuleViewMetadata))]
    public partial class SecurityModuleView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		[StringLength(200)]
		public String Description { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[InverseProperty("SecurityModule")]
		public List<SecurityAccessOptionView> SecurityAccessOption { get; set; } = new List<SecurityAccessOptionView>();
	}
}

