// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(SecurityCompanyConfigurationViewMetadata))]
    public partial class SecurityCompanyConfigurationView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		[StringLength(50)]
		public String HostEmail { get; set; }

		public Int32? PortEmail { get; set; }

		[StringLength(50)]
		public String UserEmail { get; set; }

		[StringLength(50)]
		public String PasswordEmail { get; set; }

		public Boolean? DefaultCredentialsEmail { get; set; }

		public Boolean? SSLEmail { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[InverseProperty("SecurityCompanyConfiguration")]
		public List<SecurityCompanyView> SecurityCompany { get; set; } = new List<SecurityCompanyView>();
	}
}

