// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.View.Base;
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(SecurityProfileViewMetadata))]
    public partial class SecurityProfileView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 SecurityCompanyId { get; set; }

		[StringLength(200)]
		public String Description { get; set; }

		[StringLength(100)]
		public String Rol { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[ForeignKey("SecurityCompanyId")]
		[InverseProperty("SecurityProfile")]
		public SecurityCompanyView SecurityCompany { get; set; }

		[InverseProperty("SecurityProfile")]
		public List<SecurityProfile_SecurityAccessOptionView> SecurityProfile_SecurityAccessOption { get; set; } = new List<SecurityProfile_SecurityAccessOptionView>();
	}
}

