// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(SecurityUserConfigurationViewMetadata))]
    public partial class SecurityUserConfigurationView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 Pagination { get; set; }

		public Int32 ModalPagination { get; set; }

		[StringLength(10)]
		public String Language { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? LastConnectionDate { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[InverseProperty("SecurityUserConfiguration")]
		public List<SecurityUserView> SecurityUser { get; set; } = new List<SecurityUserView>();
	}
}

