// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views;
using InfoportOneAdmon.Back.Entities.Views.Base;
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.View.Base
{
    [MetadataType(typeof(SecurityProfile_SecurityAccessOptionViewMetadata))]
    public partial class SecurityProfile_SecurityAccessOptionView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 SecurityProfileId { get; set; }

		public Int32 SecurityAccessOptionId { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[ForeignKey("SecurityAccessOptionId")]
		[InverseProperty("SecurityProfile_SecurityAccessOption")]
		public SecurityAccessOptionView SecurityAccessOption { get; set; }

		[ForeignKey("SecurityProfileId")]
		[InverseProperty("SecurityProfile_SecurityAccessOption")]
		public SecurityProfileView SecurityProfile { get; set; }
	}
}

