// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(SecurityUserViewMetadata))]
    public partial class SecurityUserView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 SecurityCompanyId { get; set; }

		[StringLength(200)]
		public String UserIdentifier { get; set; }

		[StringLength(50)]
		public String Login { get; set; }

		[StringLength(200)]
		public String Name { get; set; }

		[StringLength(200)]
		public String DisplayName { get; set; }

		[StringLength(200)]
		public String Mail { get; set; }

		[StringLength(50)]
		public String OrganizationCif { get; set; }

		[StringLength(50)]
		public String OrganizationCode { get; set; }

		[StringLength(200)]
		public String OrganizationName { get; set; }

		public Int32? SecurityUserConfigurationId { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[ForeignKey("SecurityCompanyId")]
		[InverseProperty("SecurityUser")]
		public SecurityCompanyView SecurityCompany { get; set; }

		[ForeignKey("SecurityUserConfigurationId")]
		[InverseProperty("SecurityUser")]
		public SecurityUserConfigurationView SecurityUserConfiguration { get; set; }

		[InverseProperty("SecurityUser")]
		public List<SecurityUserGridConfigurationView> SecurityUserGridConfiguration { get; set; } = new List<SecurityUserGridConfigurationView>();
	}
}

