// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(SecurityCompanyViewMetadata))]
    public partial class SecurityCompanyView: IViewBase	
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 SecurityCompanyGroupId { get; set; }

		[StringLength(200)]
		public String Name { get; set; }

		[StringLength(20)]
		public String Cif { get; set; }

		public Int32? SecurityCompanyConfigurationId { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[ForeignKey("SecurityCompanyConfigurationId")]
		[InverseProperty("SecurityCompany")]
		public SecurityCompanyConfigurationView SecurityCompanyConfiguration { get; set; }

		[ForeignKey("SecurityCompanyGroupId")]
		[InverseProperty("SecurityCompany")]
		public SecurityCompanyGroupView SecurityCompanyGroup { get; set; }

		[InverseProperty("SecurityCompany")]
		public List<SecurityProfileView> SecurityProfile { get; set; } = new List<SecurityProfileView>();

		[InverseProperty("SecurityCompany")]
		public List<SecurityUserView> SecurityUser { get; set; } = new List<SecurityUserView>();
	}
}

