// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using InfoportOneAdmon.Back.Entities.Views.Base.Metadata;
using Helix6.Base.Domain.BaseInterfaces;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InfoportOneAdmon.Back.Entities.Views.Base
{
    [MetadataType(typeof(VTA_AttachmentViewMetadata))]
    public partial class VTA_AttachmentView : IViewBase
    {
		public Int32 Id { get; set; }

		public Int32? AttachmentTypeId { get; set; }

		public Int32 EntityId { get; set; }

		[StringLength(1000)]
		public String EntityName { get; set; }

		[StringLength(2000)]
		public String EntityDescription { get; set; }

		[StringLength(1000)]
		public String FileName { get; set; }

		[StringLength(10)]
		public String FileExtension { get; set; }

		public Int32? FileSizeKb { get; set; }

		[StringLength(2000)]
		public String AttachmentDescription { get; set; }

		public Int32? AttachmentFileId { get; set; }

		[StringLength(70)]
		public String AuditCreationUser { get; set; }

		[StringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[StringLength(2000)]
		public String AttachmentType { get; set; }
	}
}

