version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - infoportone_postgres_data:/var/lib/postgresql/data
    networks:
      - InfoportOne
    ports:
      - "${POSTGRES_PORT}:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-keycloak
    restart: unless-stopped
    depends_on:
      - postgres
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - infoportone_keycloak_data:/opt/keycloak/data
    networks:
      - InfoportOne

networks:
  InfoportOne:
    name: InfoportOne
    driver: bridge

volumes:
  infoportone_postgres_data:
    name: infoportone_postgres_data
  infoportone_keycloak_data:
    name: infoportone_keycloak_data
