// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain;
using Helix6.Base.Domain.Endpoints;
using Helix6.Base.Helpers;
using InfoportOneAdmon.Back.DataModel;
using InfoportOneAdmon.Back.Entities.Views;
using InfoportOneAdmon.Back.Entities.Views.Metadata;
using InfoportOneAdmon.Back.Entities.Views.Base;
using InfoportOneAdmon.Back.Services;

namespace InfoportOneAdmon.Back.Api.Endpoints.Base.Generator
{
    public static class ApplicationEndpoints
    {
        /// <summary>
        /// Maps selected endpoints of the entity <type>Application</type>.
        /// </summary>
        /// <param name="app"></param>
        public static void MapApplicationEndpoints(this WebApplication app)
        {
            EndpointHelper.GenerateGetByIdEndpoint<ApplicationService, ApplicationView, Application, ApplicationViewMetadata>(app, "/api/Application/GetById", new EndpointAccess(HelixEnums.SecurityLevel.Read));
            EndpointHelper.GenerateGetAllEndpoint<ApplicationService, ApplicationView, Application, ApplicationViewMetadata>(app, "/api/Application/GetAll", new EndpointAccess(HelixEnums.SecurityLevel.Read));
        }
    }
}
