// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain;
using Helix6.Base.Domain.Endpoints;
using Helix6.Base.Helpers;
using InfoportOneAdmon.Back.DataModel;
using InfoportOneAdmon.Back.Entities.Views;
using InfoportOneAdmon.Back.Entities.Views.Metadata;
using InfoportOneAdmon.Back.Services;
using InfoportOneAdmon.Back.Entities.Views.Base;

namespace InfoportOneAdmon.Back.Api.Endpoints.Base.Generator
{
	public static class AuditLogEndpoints
	{
        /// <summary>
        /// Maps selected endpoints of the entity <type>AuditLog</type>.
        /// </summary>
        /// <param name="app"></param>
        public static void MapAuditLogEndpoints(this WebApplication app)
        {
            EndpointHelper.GenerateGetAllKendoFilterEndpoint<AuditLogService, AuditLogView, AuditLog, AuditLogViewMetadata>(app, "/api/AuditLog/GetAllKendoFilter", new EndpointAccess(HelixEnums.SecurityLevel.Read));
        }
	}
}