// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain;
using Helix6.Base.Domain.Endpoints;
using Helix6.Base.Helpers;
using InfoportOneAdmon.Back.DataModel;
using InfoportOneAdmon.Back.Entities.Views;
using InfoportOneAdmon.Back.Entities.Views.Metadata;
using InfoportOneAdmon.Back.Entities.Views.Base;
using InfoportOneAdmon.Back.Services;

namespace InfoportOneAdmon.Back.Api.Endpoints.Base.Generator
{
    public static class OrganizationEndpoints
    {
        /// <summary>
        /// Maps selected endpoints of the entity <type>Organization</type>.
        /// </summary>
        /// <param name="app"></param>
        public static void MapOrganizationEndpoints(this WebApplication app)
        {
            EndpointHelper.GenerateDeleteUndeleteLogicByIdEndpoint<OrganizationService, OrganizationView, Organization, OrganizationViewMetadata>(app, "/api/Organization/DeleteUndeleteLogicById", new EndpointAccess(HelixEnums.SecurityLevel.Modify));
        }
    }
}
