// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain;
using Helix6.Base.Domain.Endpoints;
using Helix6.Base.Helpers;
using InfoportOneAdmon.Back.DataModel;
using InfoportOneAdmon.Back.Entities.Views;
using InfoportOneAdmon.Back.Entities.Views.Metadata;
using InfoportOneAdmon.Back.Entities.Views.Base;
using InfoportOneAdmon.Back.Services;

namespace InfoportOneAdmon.Back.Api.Endpoints.Base.Generator
{
    public static class VTA_OrganizationEndpoints
    {
        /// <summary>
        /// Maps selected endpoints of the entity <type>VTA_Organization</type>.
        /// </summary>
        /// <param name="app"></param>
        public static void MapVTA_OrganizationEndpoints(this WebApplication app)
        {
            EndpointHelper.GenerateGetAllKendoFilterEndpoint<VTA_OrganizationService, VTA_OrganizationView, VTA_Organization, VTA_OrganizationViewMetadata>(app, "/api/VTA_Organization/GetAllKendoFilter", new EndpointAccess(HelixEnums.SecurityLevel.Read));
        }
    }
}
