// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;

namespace InfoportOneAdmon.Back.Entities.Views
{
	public partial class CourseView: IValidityEntity	
	{
		
	}
}

