// <auto-generated />
using System;
using InfoportOneAdmon.Back.Data.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfoportOneAdmon.Back.Data.Migrations
{
    [DbContext(typeof(EntityModel))]
    [Migration("20260215192054_01020001_StructureHelix")]
    partial class Migration_01020001_StructureHelix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Admon")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica requerida por Helix6 (IEntityBase)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("citext");

                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identificador único de negocio auto-generado inmutable");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.ToTable("Application", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationModule", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationRole", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationSecurity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(512)
                        .HasColumnType("citext");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationSecurity", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("AttachmentFileId")
                        .HasColumnType("integer");

                    b.Property<int?>("AttachmentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("EntityDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("FileSizeKb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentFileId");

                    b.HasIndex("AttachmentTypeId");

                    b.ToTable("Attachment", "Helix6_Attachment");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.AttachmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("FileContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AttachmentFile", "Helix6_Attachment");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.AttachmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("AttachmentType", "Helix6_Attachment");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Controller")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Module")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Profile")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecurityAccessOption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SecurityAccessOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SecurityCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecurityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SecurityModuleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityModuleId");

                    b.ToTable("SecurityAccessOption", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOptionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Controller")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SecurityAccessOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityAccessOptionId");

                    b.ToTable("SecurityAccessOptionLevel", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Cif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SecurityCompanyConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("SecurityCompanyGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityCompanyConfigurationId");

                    b.HasIndex("SecurityCompanyGroupId");

                    b.ToTable("SecurityCompany", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompanyConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<bool?>("DefaultCredentialsEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("HostEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PortEmail")
                        .HasColumnType("integer");

                    b.Property<bool?>("SSLEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("SecurityCompanyConfiguration", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompanyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SecurityCompanyGroup", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SecurityModule", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SecurityCompanyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityCompanyId");

                    b.ToTable("SecurityProfile", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityProfile_SecurityAccessOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("SecurityAccessOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("SecurityProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityAccessOptionId");

                    b.HasIndex("SecurityProfileId");

                    b.ToTable("SecurityProfile_SecurityAccessOption", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganizationCif")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrganizationCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SecurityCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecurityUserConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SecurityCompanyId");

                    b.HasIndex("SecurityUserConfigurationId");

                    b.ToTable("SecurityUser", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUserConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("LastConnectionDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("ModalPagination")
                        .HasColumnType("integer");

                    b.Property<int>("Pagination")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SecurityUserConfiguration", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUserGridConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Configuration")
                        .HasColumnType("text");

                    b.Property<bool>("DefaultConfiguration")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Entity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SecurityUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityUserId");

                    b.ToTable("SecurityUserGridConfiguration", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("SecurityVersion", "Helix6_Security");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.VTA_Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("AttachmentFileId")
                        .HasColumnType("integer");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("EntityDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("FileSizeKb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VTA_Attachment", "Helix6_Attachment");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.EventHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("LastEventHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)");

                    b.Property<DateTime>("LastPublishedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("EventHash", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica requerida por Helix6 (IEntityBase)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("citext");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("citext");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext");

                    b.Property<int>("SecurityCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identificador único inmutable de la organización. Se propaga en claim c_ids de tokens JWT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SecurityCompanyId"));

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Organization", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.OrganizationApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationModuleId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationApplicationModule", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.OrganizationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext")
                        .HasComment("Nombre del grupo de organizaciones");

                    b.HasKey("Id");

                    b.ToTable("OrganizationGroup", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.UserCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Clave primaria técnica requerida por Helix6 (IEntityBase)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Creation Date#Registry creation date");

                    b.Property<string>("AuditCreationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Creation User#Registry creation user");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Deletion Date#Logic registry deletion date");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp")
                        .HasComment("Audit - Modification Date#Last registry modification date");

                    b.Property<string>("AuditModificationUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasComment("Audit - Modification User#Registry modification User");

                    b.Property<string>("ConsolidatedCompanyIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsolidatedRoles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext");

                    b.Property<string>("LastEventHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("UserCache", "Admon");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.VTA_ActiveApplicationModules", b =>
                {
                    b.Property<string>("Acronym")
                        .HasColumnType("citext");

                    b.Property<int>("AppBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationModuleName")
                        .HasColumnType("citext");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasColumnType("citext");

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveApplicationModules", "infoportone");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.VTA_ActiveApplications", b =>
                {
                    b.Property<string>("Acronym")
                        .HasColumnType("citext");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasColumnType("citext");

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("citext");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveApplications", "infoportone");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.VTA_ActiveOrganizations", b =>
                {
                    b.Property<string>("Acronym")
                        .HasColumnType("citext");

                    b.Property<string>("Address")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasColumnType("citext");

                    b.Property<string>("City")
                        .HasColumnType("citext");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("citext");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("citext");

                    b.Property<string>("Country")
                        .HasColumnType("citext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("citext");

                    b.Property<int>("SecurityCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("TaxId")
                        .HasColumnType("citext");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveOrganizations", "infoportone");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.VTA_ApplicationSecurityCredentials", b =>
                {
                    b.Property<int>("AppBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditCreationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditCreationUser")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasColumnType("citext");

                    b.Property<string>("ClientId")
                        .HasColumnType("citext");

                    b.Property<string>("ClientType")
                        .HasColumnType("citext");

                    b.Property<string>("CredentialType")
                        .HasColumnType("citext");

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("vw_ApplicationSecurityCredentials", "infoportone");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.VTA_OrganizationModuleAccess", b =>
                {
                    b.Property<DateTime?>("AccessGrantedDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("AppBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationModuleName")
                        .HasColumnType("citext");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("citext");

                    b.Property<string>("AuditCreationUser")
                        .HasColumnType("citext");

                    b.Property<DateTime?>("AuditDeletionDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("AuditModificationDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("AuditModificationUser")
                        .HasColumnType("citext");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("citext");

                    b.Property<int>("SecurityCompanyId")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("vw_OrganizationModuleAccess", "infoportone");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationModule", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Application", "Application")
                        .WithMany("ApplicationModules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applicationmodule_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationRole", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Application", "Application")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applicationrole_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationSecurity", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Application", "Application")
                        .WithMany("ApplicationSecurities")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appsecurity_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.Attachment", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.AttachmentFile", "AttachmentFile")
                        .WithMany("Attachment")
                        .HasForeignKey("AttachmentFileId");

                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.AttachmentType", "AttachmentType")
                        .WithMany("Attachment")
                        .HasForeignKey("AttachmentTypeId");

                    b.Navigation("AttachmentFile");

                    b.Navigation("AttachmentType");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOption", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityModule", "SecurityModule")
                        .WithMany("SecurityAccessOption")
                        .HasForeignKey("SecurityModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityModule");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOptionLevel", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOption", "SecurityAccessOption")
                        .WithMany("SecurityAccessOptionLevel")
                        .HasForeignKey("SecurityAccessOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityAccessOption");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompany", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityCompanyConfiguration", "SecurityCompanyConfiguration")
                        .WithMany("SecurityCompany")
                        .HasForeignKey("SecurityCompanyConfigurationId");

                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityCompanyGroup", "SecurityCompanyGroup")
                        .WithMany("SecurityCompany")
                        .HasForeignKey("SecurityCompanyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityCompanyConfiguration");

                    b.Navigation("SecurityCompanyGroup");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityProfile", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityCompany", "SecurityCompany")
                        .WithMany("SecurityProfile")
                        .HasForeignKey("SecurityCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityCompany");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityProfile_SecurityAccessOption", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOption", "SecurityAccessOption")
                        .WithMany("SecurityProfile_SecurityAccessOption")
                        .HasForeignKey("SecurityAccessOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityProfile", "SecurityProfile")
                        .WithMany("SecurityProfile_SecurityAccessOption")
                        .HasForeignKey("SecurityProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityAccessOption");

                    b.Navigation("SecurityProfile");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUser", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityCompany", "SecurityCompany")
                        .WithMany("SecurityUser")
                        .HasForeignKey("SecurityCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityUserConfiguration", "SecurityUserConfiguration")
                        .WithMany("SecurityUser")
                        .HasForeignKey("SecurityUserConfigurationId");

                    b.Navigation("SecurityCompany");

                    b.Navigation("SecurityUserConfiguration");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUserGridConfiguration", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.Base.SecurityUser", "SecurityUser")
                        .WithMany("SecurityUserGridConfiguration")
                        .HasForeignKey("SecurityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityUser");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Organization", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.OrganizationGroup", "OrganizationGroup")
                        .WithMany("Organizations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_organization_group");

                    b.Navigation("OrganizationGroup");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.OrganizationApplicationModule", b =>
                {
                    b.HasOne("InfoportOneAdmon.Back.DataModel.ApplicationModule", "ApplicationModule")
                        .WithMany("OrganizationApplicationModules")
                        .HasForeignKey("ApplicationModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orgappmodule_module");

                    b.HasOne("InfoportOneAdmon.Back.DataModel.Organization", "Organization")
                        .WithMany("OrganizationApplicationModules")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orgappmodule_organization");

                    b.Navigation("ApplicationModule");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Application", b =>
                {
                    b.Navigation("ApplicationModules");

                    b.Navigation("ApplicationRoles");

                    b.Navigation("ApplicationSecurities");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.ApplicationModule", b =>
                {
                    b.Navigation("OrganizationApplicationModules");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.AttachmentFile", b =>
                {
                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.AttachmentType", b =>
                {
                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityAccessOption", b =>
                {
                    b.Navigation("SecurityAccessOptionLevel");

                    b.Navigation("SecurityProfile_SecurityAccessOption");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompany", b =>
                {
                    b.Navigation("SecurityProfile");

                    b.Navigation("SecurityUser");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompanyConfiguration", b =>
                {
                    b.Navigation("SecurityCompany");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityCompanyGroup", b =>
                {
                    b.Navigation("SecurityCompany");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityModule", b =>
                {
                    b.Navigation("SecurityAccessOption");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityProfile", b =>
                {
                    b.Navigation("SecurityProfile_SecurityAccessOption");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUser", b =>
                {
                    b.Navigation("SecurityUserGridConfiguration");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Base.SecurityUserConfiguration", b =>
                {
                    b.Navigation("SecurityUser");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.Organization", b =>
                {
                    b.Navigation("OrganizationApplicationModules");
                });

            modelBuilder.Entity("InfoportOneAdmon.Back.DataModel.OrganizationGroup", b =>
                {
                    b.Navigation("Organizations");
                });
#pragma warning restore 612, 618
        }
    }
}
