// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Validations.ModelValidations;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InfoportOneAdmon.Back.Entities.Views.Metadata;

namespace InfoportOneAdmon.Back.Entities.Views
{
	[MetadataType(typeof(OrganizationViewMetadata))]
	public partial class OrganizationView : IViewBase
	{
		public Int32 Id { get; set; }

		public Int32 SecurityCompanyId { get; set; }

		public String Name { get; set; }

		public String Acronym { get; set; }

		public String TaxId { get; set; }

		public String Address { get; set; }

		public String City { get; set; }

		public String Country { get; set; }

		public String ContactEmail { get; set; }

		public String ContactPhone { get; set; }

		public Int32? GroupId { get; set; }

		public String AuditCreationUser { get; set; }

		public DateTime? AuditCreationDate { get; set; }

		public String AuditModificationUser { get; set; }

		public DateTime? AuditModificationDate { get; set; }

		public DateTime? AuditDeletionDate { get; set; }

		public OrganizationGroupView Group { get; set; }

		public List<OrganizationApplicationModuleView> OrganizationApplicationModule { get; set; } = new List<OrganizationApplicationModuleView>();

	}
}

