// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Validations.ModelValidations;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InfoportOneAdmon.Back.Entities.Views.Metadata;

namespace InfoportOneAdmon.Back.Entities.Views
{
	[MetadataType(typeof(OrganizationGroupViewMetadata))]
	public partial class OrganizationGroupView : IViewBase
	{
		public Int32 Id { get; set; }

		public String Name { get; set; }

		public String AuditCreationUser { get; set; }

		public DateTime? AuditCreationDate { get; set; }

		public String AuditModificationUser { get; set; }

		public DateTime? AuditModificationDate { get; set; }

		public DateTime? AuditDeletionDate { get; set; }

		public List<OrganizationView> Organization { get; set; } = new List<OrganizationView>();

	}
}

