// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Validations.ModelValidations;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InfoportOneAdmon.Back.Entities.Views.Metadata;

namespace InfoportOneAdmon.Back.Entities.Views
{
	[MetadataType(typeof(VTA_AttachmentViewMetadata))]
    public partial class VTA_AttachmentView : IViewBase
	{
		public Int32 Id { get; set; }

		public Int32 AttachmentTypeId { get; set; }

		public Int32 EntityId { get; set; }

		[HelixStringLength(1000)]
		public String EntityName { get; set; }

		[HelixStringLength(2000)]
		public String EntityDescription { get; set; }

		[HelixStringLength(1000)]
		public String FileName { get; set; }

		[HelixStringLength(10)]
		public String FileExtension { get; set; }

		public Int32? FileSizeKb { get; set; }

		[HelixStringLength(2000)]
		public String AttachmentDescription { get; set; }

		public Int32? AttachmentFileId { get; set; }

		[HelixStringLength(70)]
		public String AuditCreationUser { get; set; }

		[HelixStringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[HelixStringLength(2000)]
		public String AttachmentType { get; set; }
	}
}

