// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Validations.ModelValidations;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InfoportOneAdmon.Back.Entities.Views.Metadata;

namespace InfoportOneAdmon.Back.Entities.Views
{
	[MetadataType(typeof(WorkerAddressViewMetadata))]
    public partial class WorkerAddressView : IViewBase
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 WorkerId { get; set; }

		[HelixStringLength(1000)]
		public String Address { get; set; }

		public Int32 AddressTypeId { get; set; }

		[HelixStringLength(70)]
		public String AuditCreationUser { get; set; }

		[HelixStringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[ForeignKey("AddressTypeId")]
		[InverseProperty("WorkerAddress")]
		public AddressTypeView AddressType { get; set; }

		[ForeignKey("WorkerId")]
		[InverseProperty("WorkerAddress")]
		public WorkerView Worker { get; set; }
	}
}

