// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Validations.ModelValidations;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InfoportOneAdmon.Back.Entities.Views.Metadata;

namespace InfoportOneAdmon.Back.Entities.Views
{
	[MetadataType(typeof(WorkerViewMetadata))]
    public partial class WorkerView : IViewBase
	{
		[Key]
		public Int32 Id { get; set; }

		[HelixStringLength(500)]
		public String Name { get; set; }

		[HelixStringLength(200)]
		public String Surnames { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime BirthDate { get; set; }

		public Boolean IsTrainee { get; set; }

		public Int32 WorkerTypeId { get; set; }

		public Int32? Age { get; set; }

		[Column(TypeName = "decimal(4, 2)")]
		public Decimal? Height { get; set; }

		[HelixStringLength(70)]
		public String AuditCreationUser { get; set; }

		[HelixStringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[InverseProperty("Worker")]
		public List<WorkerAddressView> WorkerAddress { get; set; } = new List<WorkerAddressView>();

		[ForeignKey("WorkerTypeId")]
		[InverseProperty("Worker")]
		public WorkerTypeView WorkerType { get; set; }

		[InverseProperty("Worker")]
		public List<Worker_CourseView> Worker_Course { get; set; } = new List<Worker_CourseView>();

		[InverseProperty("Worker")]
		public List<Worker_ProjectView> Worker_Project { get; set; } = new List<Worker_ProjectView>();
	}
}

