// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Helix 6 Generator.
//  
//     Changes to this file could cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Helix6.Base.Domain.BaseInterfaces;
using Helix6.Base.Domain.Validations.ModelValidations;
using Mapster;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InfoportOneAdmon.Back.Entities.Views.Metadata;

namespace InfoportOneAdmon.Back.Entities.Views
{
	[MetadataType(typeof(Worker_CourseViewMetadata))]
    public partial class Worker_CourseView : IViewBase
	{
		[Key]
		public Int32 Id { get; set; }

		public Int32 WorkerId { get; set; }

		public Int32 CourseId { get; set; }

		[HelixStringLength(70)]
		public String AuditCreationUser { get; set; }

		[HelixStringLength(70)]
		public String AuditModificationUser { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditCreationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditModificationDate { get; set; }

		[Column(TypeName = "datetime")]
		public DateTime? AuditDeletionDate { get; set; }

		[ForeignKey("CourseId")]
		[InverseProperty("Worker_Course")]
		public CourseView Course { get; set; }

		[ForeignKey("WorkerId")]
		[InverseProperty("Worker_Course")]
		public WorkerView Worker { get; set; }
	}
}

