# Etapa 1: build del proyecto
FROM node:22.12.0 AS build-stage
# Configure time-zone
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

ARG KENDO_UI_LICENSE
ENV KENDO_UI_LICENSE=$KENDO_UI_LICENSE


# Copia el archivo .npmrc.template al contenedor y lo renombra
COPY .npmrc.template /root/.npmrc

# RUN echo "Contenido de /root/.npmrc:" &&  cat /root/.npmrc

COPY package.json package-lock.json ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.spec.json ./

 


# Activate Kendo license
RUN npx kendo-ui-license activate

RUN npm install && rm -f /root/.npmrc


COPY . .
RUN npm run build --prod

# Etapa 2: Nginx para servir la app
FROM nginx:alpine AS production-stage


COPY --from=build-stage /app/dist/helix6-v2-front/browser /usr/share/nginx/html

# Copia el archivo de configuración personalizado de Nginx
COPY default.conf /etc/nginx/conf.d/default.conf

# Copiar el archivo .env al contenedor
COPY web.env /usr/share/nginx/html/web.env
# Copiar el archivo entrypoint que permitirá cargar las variables de entorno
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Image Metadata
LABEL infoport.vendor="Infoport"

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 80

