
CREATE EXTENSION IF NOT EXISTS citext;

CREATE SCHEMA IF NOT EXISTS "Admon";

-- APPLICATION
CREATE TABLE IF NOT EXISTS "Admon"."Application" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AppName" citext NOT NULL,
    "Description" citext NULL,
    "RolePrefix" citext NOT NULL,
    "AuditCreationUser" citext NULL,
    "AuditCreationDate" timestamptz NULL,
    "AuditModificationUser" citext NULL,
    "AuditModificationDate" timestamptz NULL,
    "AuditDeletionDate" timestamptz NULL,

    CONSTRAINT "UX_Application_AppName" UNIQUE ("AppName"),
    CONSTRAINT "UX_Application_RolePrefix" UNIQUE ("RolePrefix"),

    CONSTRAINT "CK_Application_AppName_len" CHECK (length("AppName") <= 100),
    CONSTRAINT "CK_Application_Description_len" CHECK (length("Description") <= 500),
    CONSTRAINT "CK_Application_RolePrefix_len" CHECK (length("RolePrefix") <= 10),
    CONSTRAINT "CK_Application_AuditCreationUser_len" CHECK (length("AuditCreationUser") <= 255),
    CONSTRAINT "CK_Application_AuditModificationUser_len" CHECK (length("AuditModificationUser") <= 255)
);

-- AUDIT LOG
CREATE TABLE IF NOT EXISTS "Admon"."AuditLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityType" citext NOT NULL,
    "EntityId" citext NOT NULL,
    "Action" citext NOT NULL,
    "UserLogin" citext NOT NULL,
    "Timestamp" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "Content" citext NULL,
    "AuditCreationUser" citext NULL,
    "AuditCreationDate" timestamptz NULL,
    "AuditModificationUser" citext NULL,
    "AuditModificationDate" timestamptz NULL,
    "AuditDeletionDate" timestamptz NULL,

    CONSTRAINT "CK_AuditLog_EntityType_len" CHECK (length("EntityType") <= 50),
    CONSTRAINT "CK_AuditLog_EntityId_len" CHECK (length("EntityId") <= 50),
    CONSTRAINT "CK_AuditLog_Action_len" CHECK (length("Action") <= 100),
    CONSTRAINT "CK_AuditLog_UserLogin_len" CHECK (length("UserLogin") <= 50),
    CONSTRAINT "CK_AuditLog_Content_len" CHECK (length("Content") <= 1000),
    CONSTRAINT "CK_AuditLog_AuditCreationUser_len" CHECK (length("AuditCreationUser") <= 255),
    CONSTRAINT "CK_AuditLog_AuditModificationUser_len" CHECK (length("AuditModificationUser") <= 255)
);

-- ORGANIZATION GROUP
CREATE TABLE IF NOT EXISTS "Admon"."OrganizationGroup" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GroupName" citext NOT NULL,
    "Description" citext NULL,
    "AuditCreationUser" citext NULL,
    "AuditCreationDate" timestamptz NULL,
    "AuditModificationUser" citext NULL,
    "AuditModificationDate" timestamptz NULL,
    "AuditDeletionDate" timestamptz NULL,

    CONSTRAINT "UX_OrganizationGroup_GroupName" UNIQUE ("GroupName"),

    CONSTRAINT "CK_OrganizationGroup_GroupName_len" CHECK (length("GroupName") <= 200),
    CONSTRAINT "CK_OrganizationGroup_Description_len" CHECK (length("Description") <= 500),
    CONSTRAINT "CK_OrganizationGroup_AuditCreationUser_len" CHECK (length("AuditCreationUser") <= 255),
    CONSTRAINT "CK_OrganizationGroup_AuditModificationUser_len" CHECK (length("AuditModificationUser") <= 255)
);

-- APPLICATION MODULE
CREATE TABLE IF NOT EXISTS "Admon"."ApplicationModule" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ApplicationId" integer NOT NULL,
    "ModuleName" citext NOT NULL,
    "Description" citext NULL,
    "DisplayOrder" integer DEFAULT 0 NULL,
    "AuditCreationUser" citext NULL,
    "AuditCreationDate" timestamptz NULL,
    "AuditModificationUser" citext NULL,
    "AuditModificationDate" timestamptz NULL,
    "AuditDeletionDate" timestamptz NULL,

    CONSTRAINT "UX_ApplicationModule_AppId_ModuleName"
        UNIQUE ("ApplicationId","ModuleName"),

    CONSTRAINT "CK_ApplicationModule_ModuleName_len" CHECK (length("ModuleName") <= 100),
    CONSTRAINT "CK_ApplicationModule_Description_len" CHECK (length("Description") <= 500),
    CONSTRAINT "CK_ApplicationModule_AuditCreationUser_len" CHECK (length("AuditCreationUser") <= 255),
    CONSTRAINT "CK_ApplicationModule_AuditModificationUser_len" CHECK (length("AuditModificationUser") <= 255),

    CONSTRAINT "FK_ApplicationModule_Application"
        FOREIGN KEY ("ApplicationId")
        REFERENCES "Admon"."Application"("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_ApplicationModule_ApplicationId"
ON "Admon"."ApplicationModule" ("ApplicationId");

-- ORGANIZATION
CREATE TABLE IF NOT EXISTS "Admon"."Organization" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SecurityCompanyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" integer NULL,
    "Name" citext NOT NULL,
    "Acronym" citext NULL,
    "TaxId" citext NOT NULL,
    "Address" citext NULL,
    "City" citext NULL,
    "PostalCode" citext NULL,
    "Country" citext NULL,
    "ContactEmail" citext NULL,
    "ContactPhone" citext NULL,
    "AuditCreationUser" citext NULL,
    "AuditCreationDate" timestamptz NULL,
    "AuditModificationUser" citext NULL,
    "AuditModificationDate" timestamptz NULL,
    "AuditDeletionDate" timestamptz NULL,

    CONSTRAINT "UX_Organization_Name" UNIQUE ("Name"),
    CONSTRAINT "UX_Organization_SecurityCompanyId" UNIQUE ("SecurityCompanyId"),
    CONSTRAINT "UX_Organization_TaxId" UNIQUE ("TaxId"),

    CONSTRAINT "CK_Organization_Name_len" CHECK (length("Name") <= 200),
    CONSTRAINT "CK_Organization_Acronym_len" CHECK (length("Acronym") <= 50),
    CONSTRAINT "CK_Organization_TaxId_len" CHECK (length("TaxId") <= 50),
    CONSTRAINT "CK_Organization_Address_len" CHECK (length("Address") <= 300),
    CONSTRAINT "CK_Organization_City_len" CHECK (length("City") <= 100),
    CONSTRAINT "CK_Organization_PostalCode_len" CHECK (length("PostalCode") <= 20),
    CONSTRAINT "CK_Organization_Country_len" CHECK (length("Country") <= 100),
    CONSTRAINT "CK_Organization_ContactEmail_len" CHECK (length("ContactEmail") <= 255),
    CONSTRAINT "CK_Organization_ContactPhone_len" CHECK (length("ContactPhone") <= 50),
    CONSTRAINT "CK_Organization_AuditCreationUser_len" CHECK (length("AuditCreationUser") <= 255),
    CONSTRAINT "CK_Organization_AuditModificationUser_len" CHECK (length("AuditModificationUser") <= 255),

    CONSTRAINT "FK_Organization_OrganizationGroup"
        FOREIGN KEY ("GroupId")
        REFERENCES "Admon"."OrganizationGroup"("Id")
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Organization_GroupId"
ON "Admon"."Organization" ("GroupId");

-- ORGANIZATION APPLICATION MODULE
CREATE TABLE IF NOT EXISTS "Admon"."Organization_ApplicationModule" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ApplicationModuleId" integer NOT NULL,
    "OrganizationId" integer NOT NULL,
    "AuditCreationUser" citext NULL,
    "AuditCreationDate" timestamptz NULL,
    "AuditModificationUser" citext NULL,
    "AuditModificationDate" timestamptz NULL,
    "AuditDeletionDate" timestamptz NULL,

    CONSTRAINT "UX_OrgAppModule_ModuleId_OrgId"
        UNIQUE ("ApplicationModuleId","OrganizationId"),

    CONSTRAINT "CK_OrgAppModule_AuditCreationUser_len" CHECK (length("AuditCreationUser") <= 255),
    CONSTRAINT "CK_OrgAppModule_AuditModificationUser_len" CHECK (length("AuditModificationUser") <= 255),

    CONSTRAINT "FK_OrgAppModule_ApplicationModule"
        FOREIGN KEY ("ApplicationModuleId")
        REFERENCES "Admon"."ApplicationModule"("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_OrgAppModule_Organization"
        FOREIGN KEY ("OrganizationId")
        REFERENCES "Admon"."Organization"("Id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_OrgAppModule_OrganizationId"
ON "Admon"."Organization_ApplicationModule" ("OrganizationId");

-- VIEW
CREATE OR REPLACE VIEW "Admon"."VTA_Organization" AS
SELECT
    o."Id",
    o."SecurityCompanyId",
    og."GroupName",
    o."Name",
    o."Acronym",
    o."TaxId",
    o."Address",
    o."City",
    o."PostalCode",
    o."Country",
    o."ContactEmail",
    o."ContactPhone",
    o."AuditCreationUser",
    o."AuditCreationDate",
    o."AuditModificationUser",
    o."AuditModificationDate",
    o."AuditDeletionDate",
    COALESCE((
        SELECT count(DISTINCT oam2."ApplicationModuleId")
        FROM "Admon"."Organization_ApplicationModule" oam2
        WHERE oam2."OrganizationId" = o."Id"
          AND oam2."AuditDeletionDate" IS NULL
    ),0)::integer AS "ModuleCount",
    COALESCE((
        SELECT count(DISTINCT am2."ApplicationId")
        FROM "Admon"."Organization_ApplicationModule" oam3
        JOIN "Admon"."ApplicationModule" am2
            ON am2."Id" = oam3."ApplicationModuleId"
        JOIN "Admon"."Application" a2
            ON a2."Id" = am2."ApplicationId"
        WHERE oam3."OrganizationId" = o."Id"
          AND oam3."AuditDeletionDate" IS NULL
          AND am2."AuditDeletionDate" IS NULL
          AND a2."AuditDeletionDate" IS NULL
    ),0)::integer AS "AppCount",
    COALESCE((
        SELECT string_agg(DISTINCT a2."AppName"::text,' / ' ORDER BY a2."AppName"::text)
        FROM "Admon"."Organization_ApplicationModule" oam4
        JOIN "Admon"."ApplicationModule" am3
            ON am3."Id" = oam4."ApplicationModuleId"
        JOIN "Admon"."Application" a2
            ON a2."Id" = am3."ApplicationId"
        WHERE oam4."OrganizationId" = o."Id"
          AND oam4."AuditDeletionDate" IS NULL
          AND am3."AuditDeletionDate" IS NULL
          AND a2."AuditDeletionDate" IS NULL
    ),'') AS "AppList"
FROM "Admon"."Organization" o
LEFT JOIN "Admon"."OrganizationGroup" og
    ON og."Id" = o."GroupId";
